import com.pengrad.telegrambot.TelegramBot
import com.pengrad.telegrambot.request.SendMessage

const val TELEGRAM_BOT_TOKEN = "5930610065:AAGn-Rls4_wxzO1cU6cOmD3oR0gaohX6ay4"

const val MEGABOX_CLIENT_CHAT_ID = "-1001820329036"
const val KTX_CLIENT_CHAT_ID = "-947068919"

const val ADMIN_CHAT_ID = "1052011050"
const val KTX_URL = "https://www.letskorail.com/ebizprd/EbizPrdTicketPr21111_i1.do"

const val SEOUL_TO_ANDONG =
    "txtGoStartCode=0090&txtGoEndCode=0526&radJobId=1&selGoTrain=05&txtSeatAttCd_4=015&txtSeatAttCd_3=000&txtSeatAttCd_2=000&txtPsgFlg_2=0&txtPsgFlg_3=0&txtPsgFlg_4=0&txtPsgFlg_5=0&chkCpn=N&selGoSeat1=015&selGoSeat2=&txtPsgCnt1=1&txtPsgCnt2=0&txtGoPage=1&txtGoAbrdDt=20240224&selGoRoom=&useSeatFlg=&useServiceFlg=&checkStnNm=Y&txtMenuId=11&SeandYo=&txtGoStartCode2=&txtGoEndCode2=&hidEasyTalk=&txtGoStart=%EC%B2%AD%EB%9F%89%EB%A6%AC&txtGoEnd=%EC%95%88%EB%8F%99&start=2024.2.24&selGoHour=04&txtGoHour=040000&selGoYear=2024&selGoMonth=02&selGoDay=24&txtGoYoil=%ED%86%A0&txtPsgFlg_1=1"

const val SUSEO_TO_BUSAN =
    "hidNormalRsv=&hidBiztransferRsv=&srTOrder=&hidDiscount=&selGoTrain=05&txtPsgFlg_1=1&txtPsgFlg_2=0&txtPsgFlg_8=0&txtPsgFlg_3=0&txtPsgFlg_4=0&txtPsgFlg_5=0&txtSeatAttCd_3=000&txtSeatAttCd_2=000&txtSeatAttCd_4=015&selGoTrainRa=05&radJobId=1&txtGoStart=%EC%88%98%EC%84%9C&txtGoEnd=%EB%B6%80%EC%82%B0&txtGoStartCode=&txtGoEndCode=&selGoYear=2024&selGoMonth=02&selGoDay=08&selGoHour=14&txtGoHour=140000&txtGoYoil=%EB%AA%A9&ret_url=&selGoSeat1=015&selGoSeat2=&txtPsgCnt1=1&txtPsgCnt2=0&txtGoPage=1&txtGoAbrdDt=20240208&selGoRoom=&useSeatFlg=&useServiceFlg=&checkStnNm=Y&SeandYo=&txtGoStartCode2=&txtGoEndCode2=&txtPnrNo=&hidStlFlg=&chkTrnSeq=&chkChgTrn1=&chkChgTrn2=&chkBtnImgTrn1=&chkBtnImgTrn2=&chkInitFlg=Y&txtMenuId=11&ra=1&txtSeatAttCd1=&txtSeatAttCd2=&txtSeatAttCd3=&txtSeatAttCd4=&txtSeatAttCd4_1=&txtSeatAttCd5=&strChkCpn=N&txtTotPsgCnt=&txtSrcarCnt=0&txtSrcarCnt1=0&txtSrcarNo1=&txtSrcarNo2=&txtSrcarNo3=&txtSrcarNo4=&txtSrcarNo5=&txtSrcarNo6=&txtSrcarNo7=&txtSrcarNo8=&txtSrcarNo9=&txtSeatNo1=&txtSeatNo2=&txtSeatNo3=&txtSeatNo4=&txtSeatNo5=&txtSeatNo6=&txtSeatNo7=&txtSeatNo8=&txtSeatNo9=&txtSrcarNo1_1=&txtSrcarNo1_2=&txtSrcarNo1_3=&txtSrcarNo1_4=&txtSrcarNo1_5=&txtSrcarNo1_6=&txtSrcarNo1_7=&txtSrcarNo1_8=&txtSrcarNo1_9=&txtSeatNo1_1=&txtSeatNo1_2=&txtSeatNo1_3=&txtSeatNo1_4=&txtSeatNo1_5=&txtSeatNo1_6=&txtSeatNo1_7=&txtSeatNo1_8=&txtSeatNo1_9=&txtDmdSeatAtt1=&txtDmdSeatAtt2=&txtDmdSeatAtt3=&txtDmdSeatAtt4=&txtDmdSeatAtt5=&txtDmdSeatAtt6=&txtDmdSeatAtt7=&txtDmdSeatAtt8=&txtDmdSeatAtt9=&txtDmdSeatAtt1_1=&txtDmdSeatAtt1_2=&txtDmdSeatAtt1_3=&txtDmdSeatAtt1_4=&txtDmdSeatAtt1_5=&txtDmdSeatAtt1_6=&txtDmdSeatAtt1_7=&txtDmdSeatAtt1_8=&txtDmdSeatAtt1_9=&hidRsvChgNo=&hidRsvTpCd=03&txtPsgTpCd1=1&txtPsgTpCd2=3&txtPsgTpCd3=1&txtPsgTpCd4=&txtPsgTpCd5=1&txtPsgTpCd6=&txtPsgTpCd7=1&txtPsgTpCd8=3&txtPsgTpCd9=&txtDiscKndCd1=000&txtDiscKndCd2=000&txtDiscKndCd3=111&txtDiscKndCd4=&txtDiscKndCd5=131&txtDiscKndCd6=&txtDiscKndCd7=112&txtDiscKndCd8=321&txtDiscKndCd9=&txtCompaCnt1=0&txtCompaCnt2=0&txtCompaCnt3=0&txtCompaCnt4=0&txtCompaCnt5=0&txtCompaCnt6=0&txtCompaCnt7=0&txtCompaCnt8=0&txtCompaCnt9=&txtStndFlg=&txtJobId=&txtJrnyCnt=&txtDptStnConsOrdr1=&txtArvStnConsOrdr1=&txtDptStnRunOrdr1=&txtArvStnRunOrdr1=&txtDptStnConsOrdr2=&txtArvStnConsOrdr2=&txtDptStnRunOrdr2=&txtArvStnRunOrdr2=&txtPsrmClCd1=&txtJrnySqno1=&txtJrnyTpCd1=&txtDptDt1=&txtDptRsStnCd1=&txtDptRsStnCdNm1=&txtDptTm1=&txtArvRsStnCd1=&txtArvRsStnCdNm1=&txtArvTm1=&txtTrnNo1=&txtRunDt1=&txtTrnClsfCd1=&txtTrnGpCd1=&txtChgFlg1=&txtDoTrnFlg1=&txtPsrmClCd2=&txtJrnySqno2=&txtJrnyTpCd2=&txtDptDt2=&txtDptRsStnCd2=&txtDptRsStnCdNm2=&txtDptTm2=&txtArvRsStnCd2=&txtArvRsStnCdNm2=&txtArvTm2=&txtTrnNo2=&txtRunDt2=&txtTrnClsfCd2=&txtTrnGpCd2=&txtChgFlg2=&txtDoTrnFlg2=&selGoStartDay=&strHmac=&PageInx=&hidEasyTalk=&hidCapFlag=\n"

const val BUSAN_TO_SUSEO =
    "hidNormalRsv=&hidBiztransferRsv=&srTOrder=&hidDiscount=&selGoTrain=05&txtPsgFlg_1=1&txtPsgFlg_2=0&txtPsgFlg_8=0&txtPsgFlg_3=0&txtPsgFlg_4=0&txtPsgFlg_5=0&txtSeatAttCd_3=000&txtSeatAttCd_2=000&txtSeatAttCd_4=015&selGoTrainRa=05&radJobId=1&txtGoStart=%EB%B6%80%EC%82%B0&txtGoEnd=%EC%88%98%EC%84%9C&txtGoStartCode=&txtGoEndCode=&selGoYear=2024&selGoMonth=02&selGoDay=12&selGoHour=17&txtGoHour=170000&txtGoYoil=%EC%9B%94&ret_url=&selGoSeat1=015&selGoSeat2=&txtPsgCnt1=1&txtPsgCnt2=0&txtGoPage=1&txtGoAbrdDt=20240212&selGoRoom=&useSeatFlg=&useServiceFlg=&checkStnNm=Y&SeandYo=&txtGoStartCode2=&txtGoEndCode2=&txtPnrNo=&hidStlFlg=&chkTrnSeq=&chkChgTrn1=&chkChgTrn2=&chkBtnImgTrn1=&chkBtnImgTrn2=&chkInitFlg=Y&txtMenuId=11&ra=1&txtSeatAttCd1=&txtSeatAttCd2=&txtSeatAttCd3=&txtSeatAttCd4=&txtSeatAttCd4_1=&txtSeatAttCd5=&strChkCpn=N&txtTotPsgCnt=&txtSrcarCnt=0&txtSrcarCnt1=0&txtSrcarNo1=&txtSrcarNo2=&txtSrcarNo3=&txtSrcarNo4=&txtSrcarNo5=&txtSrcarNo6=&txtSrcarNo7=&txtSrcarNo8=&txtSrcarNo9=&txtSeatNo1=&txtSeatNo2=&txtSeatNo3=&txtSeatNo4=&txtSeatNo5=&txtSeatNo6=&txtSeatNo7=&txtSeatNo8=&txtSeatNo9=&txtSrcarNo1_1=&txtSrcarNo1_2=&txtSrcarNo1_3=&txtSrcarNo1_4=&txtSrcarNo1_5=&txtSrcarNo1_6=&txtSrcarNo1_7=&txtSrcarNo1_8=&txtSrcarNo1_9=&txtSeatNo1_1=&txtSeatNo1_2=&txtSeatNo1_3=&txtSeatNo1_4=&txtSeatNo1_5=&txtSeatNo1_6=&txtSeatNo1_7=&txtSeatNo1_8=&txtSeatNo1_9=&txtDmdSeatAtt1=&txtDmdSeatAtt2=&txtDmdSeatAtt3=&txtDmdSeatAtt4=&txtDmdSeatAtt5=&txtDmdSeatAtt6=&txtDmdSeatAtt7=&txtDmdSeatAtt8=&txtDmdSeatAtt9=&txtDmdSeatAtt1_1=&txtDmdSeatAtt1_2=&txtDmdSeatAtt1_3=&txtDmdSeatAtt1_4=&txtDmdSeatAtt1_5=&txtDmdSeatAtt1_6=&txtDmdSeatAtt1_7=&txtDmdSeatAtt1_8=&txtDmdSeatAtt1_9=&hidRsvChgNo=&hidRsvTpCd=03&txtPsgTpCd1=1&txtPsgTpCd2=3&txtPsgTpCd3=1&txtPsgTpCd4=&txtPsgTpCd5=1&txtPsgTpCd6=&txtPsgTpCd7=1&txtPsgTpCd8=3&txtPsgTpCd9=&txtDiscKndCd1=000&txtDiscKndCd2=000&txtDiscKndCd3=111&txtDiscKndCd4=&txtDiscKndCd5=131&txtDiscKndCd6=&txtDiscKndCd7=112&txtDiscKndCd8=321&txtDiscKndCd9=&txtCompaCnt1=0&txtCompaCnt2=0&txtCompaCnt3=0&txtCompaCnt4=0&txtCompaCnt5=0&txtCompaCnt6=0&txtCompaCnt7=0&txtCompaCnt8=0&txtCompaCnt9=&txtStndFlg=&txtJobId=&txtJrnyCnt=&txtDptStnConsOrdr1=&txtArvStnConsOrdr1=&txtDptStnRunOrdr1=&txtArvStnRunOrdr1=&txtDptStnConsOrdr2=&txtArvStnConsOrdr2=&txtDptStnRunOrdr2=&txtArvStnRunOrdr2=&txtPsrmClCd1=&txtJrnySqno1=&txtJrnyTpCd1=&txtDptDt1=&txtDptRsStnCd1=&txtDptRsStnCdNm1=&txtDptTm1=&txtArvRsStnCd1=&txtArvRsStnCdNm1=&txtArvTm1=&txtTrnNo1=&txtRunDt1=&txtTrnClsfCd1=&txtTrnGpCd1=&txtChgFlg1=&txtDoTrnFlg1=&txtPsrmClCd2=&txtJrnySqno2=&txtJrnyTpCd2=&txtDptDt2=&txtDptRsStnCd2=&txtDptRsStnCdNm2=&txtDptTm2=&txtArvRsStnCd2=&txtArvRsStnCdNm2=&txtArvTm2=&txtTrnNo2=&txtRunDt2=&txtTrnClsfCd2=&txtTrnGpCd2=&txtChgFlg2=&txtDoTrnFlg2=&selGoStartDay=&strHmac=&PageInx=&hidEasyTalk=&hidCapFlag=\n"

const val SEOUL_TO_JUNJU =
    "hidNormalRsv=&hidBiztransferRsv=&srTOrder=&hidDiscount=&selGoTrain=05&txtPsgFlg_1=1&txtPsgFlg_2=0&txtPsgFlg_8=0&txtPsgFlg_3=0&txtPsgFlg_4=0&txtPsgFlg_5=0&txtSeatAttCd_3=000&txtSeatAttCd_2=000&txtSeatAttCd_4=015&selGoTrainRa=05&radJobId=1&txtGoStart=%EC%84%9C%EC%9A%B8&txtGoEnd=%EC%A0%84%EC%A3%BC&txtGoStartCode=&txtGoEndCode=0045&selGoYear=2024&selGoMonth=02&selGoDay=08&selGoHour=16&txtGoHour=160000&txtGoYoil=%EB%AA%A9&ret_url=&selGoSeat1=015&selGoSeat2=&txtPsgCnt1=1&txtPsgCnt2=0&txtGoPage=1&txtGoAbrdDt=20240208&selGoRoom=&useSeatFlg=&useServiceFlg=&checkStnNm=Y&SeandYo=N&txtGoStartCode2=&txtGoEndCode2=&txtPnrNo=&hidStlFlg=&chkTrnSeq=&chkChgTrn1=&chkChgTrn2=&chkBtnImgTrn1=&chkBtnImgTrn2=&chkInitFlg=Y&txtMenuId=11&ra=1&txtSeatAttCd1=&txtSeatAttCd2=&txtSeatAttCd3=&txtSeatAttCd4=&txtSeatAttCd4_1=&txtSeatAttCd5=&strChkCpn=N&txtTotPsgCnt=&txtSrcarCnt=0&txtSrcarCnt1=0&txtSrcarNo1=&txtSrcarNo2=&txtSrcarNo3=&txtSrcarNo4=&txtSrcarNo5=&txtSrcarNo6=&txtSrcarNo7=&txtSrcarNo8=&txtSrcarNo9=&txtSeatNo1=&txtSeatNo2=&txtSeatNo3=&txtSeatNo4=&txtSeatNo5=&txtSeatNo6=&txtSeatNo7=&txtSeatNo8=&txtSeatNo9=&txtSrcarNo1_1=&txtSrcarNo1_2=&txtSrcarNo1_3=&txtSrcarNo1_4=&txtSrcarNo1_5=&txtSrcarNo1_6=&txtSrcarNo1_7=&txtSrcarNo1_8=&txtSrcarNo1_9=&txtSeatNo1_1=&txtSeatNo1_2=&txtSeatNo1_3=&txtSeatNo1_4=&txtSeatNo1_5=&txtSeatNo1_6=&txtSeatNo1_7=&txtSeatNo1_8=&txtSeatNo1_9=&txtDmdSeatAtt1=&txtDmdSeatAtt2=&txtDmdSeatAtt3=&txtDmdSeatAtt4=&txtDmdSeatAtt5=&txtDmdSeatAtt6=&txtDmdSeatAtt7=&txtDmdSeatAtt8=&txtDmdSeatAtt9=&txtDmdSeatAtt1_1=&txtDmdSeatAtt1_2=&txtDmdSeatAtt1_3=&txtDmdSeatAtt1_4=&txtDmdSeatAtt1_5=&txtDmdSeatAtt1_6=&txtDmdSeatAtt1_7=&txtDmdSeatAtt1_8=&txtDmdSeatAtt1_9=&hidRsvChgNo=&hidRsvTpCd=03&txtPsgTpCd1=1&txtPsgTpCd2=3&txtPsgTpCd3=1&txtPsgTpCd4=&txtPsgTpCd5=1&txtPsgTpCd6=&txtPsgTpCd7=1&txtPsgTpCd8=3&txtPsgTpCd9=&txtDiscKndCd1=000&txtDiscKndCd2=000&txtDiscKndCd3=111&txtDiscKndCd4=&txtDiscKndCd5=131&txtDiscKndCd6=&txtDiscKndCd7=112&txtDiscKndCd8=321&txtDiscKndCd9=&txtCompaCnt1=0&txtCompaCnt2=0&txtCompaCnt3=0&txtCompaCnt4=0&txtCompaCnt5=0&txtCompaCnt6=0&txtCompaCnt7=0&txtCompaCnt8=0&txtCompaCnt9=&txtStndFlg=&txtJobId=&txtJrnyCnt=&txtDptStnConsOrdr1=&txtArvStnConsOrdr1=&txtDptStnRunOrdr1=&txtArvStnRunOrdr1=&txtDptStnConsOrdr2=&txtArvStnConsOrdr2=&txtDptStnRunOrdr2=&txtArvStnRunOrdr2=&txtPsrmClCd1=&txtJrnySqno1=&txtJrnyTpCd1=&txtDptDt1=&txtDptRsStnCd1=&txtDptRsStnCdNm1=&txtDptTm1=&txtArvRsStnCd1=&txtArvRsStnCdNm1=&txtArvTm1=&txtTrnNo1=&txtRunDt1=&txtTrnClsfCd1=&txtTrnGpCd1=&txtChgFlg1=&txtDoTrnFlg1=&txtPsrmClCd2=&txtJrnySqno2=&txtJrnyTpCd2=&txtDptDt2=&txtDptRsStnCd2=&txtDptRsStnCdNm2=&txtDptTm2=&txtArvRsStnCd2=&txtArvRsStnCdNm2=&txtArvTm2=&txtTrnNo2=&txtRunDt2=&txtTrnClsfCd2=&txtTrnGpCd2=&txtChgFlg2=&txtDoTrnFlg2=&selGoStartDay=&strHmac=&PageInx=&hidEasyTalk=&hidCapFlag=\n"
const val YOUNGSAN_TO_JUNJU =
    "hidNormalRsv=&hidBiztransferRsv=&srTOrder=&hidDiscount=&selGoTrain=05&txtPsgFlg_1=1&txtPsgFlg_2=0&txtPsgFlg_8=0&txtPsgFlg_3=0&txtPsgFlg_4=0&txtPsgFlg_5=0&txtSeatAttCd_3=000&txtSeatAttCd_2=000&txtSeatAttCd_4=015&selGoTrainRa=05&radJobId=1&txtGoStart=%EC%9A%A9%EC%82%B0&txtGoEnd=%EC%A0%84%EC%A3%BC&txtGoStartCode=&txtGoEndCode=&selGoYear=2024&selGoMonth=02&selGoDay=08&selGoHour=14&txtGoHour=140000&txtGoYoil=%EB%AA%A9&ret_url=&selGoSeat1=015&selGoSeat2=&txtPsgCnt1=1&txtPsgCnt2=0&txtGoPage=1&txtGoAbrdDt=20240208&selGoRoom=&useSeatFlg=&useServiceFlg=&checkStnNm=Y&SeandYo=N&txtGoStartCode2=&txtGoEndCode2=&txtPnrNo=&hidStlFlg=&chkTrnSeq=&chkChgTrn1=&chkChgTrn2=&chkBtnImgTrn1=&chkBtnImgTrn2=&chkInitFlg=Y&txtMenuId=11&ra=1&txtSeatAttCd1=&txtSeatAttCd2=&txtSeatAttCd3=&txtSeatAttCd4=&txtSeatAttCd4_1=&txtSeatAttCd5=&strChkCpn=N&txtTotPsgCnt=&txtSrcarCnt=0&txtSrcarCnt1=0&txtSrcarNo1=&txtSrcarNo2=&txtSrcarNo3=&txtSrcarNo4=&txtSrcarNo5=&txtSrcarNo6=&txtSrcarNo7=&txtSrcarNo8=&txtSrcarNo9=&txtSeatNo1=&txtSeatNo2=&txtSeatNo3=&txtSeatNo4=&txtSeatNo5=&txtSeatNo6=&txtSeatNo7=&txtSeatNo8=&txtSeatNo9=&txtSrcarNo1_1=&txtSrcarNo1_2=&txtSrcarNo1_3=&txtSrcarNo1_4=&txtSrcarNo1_5=&txtSrcarNo1_6=&txtSrcarNo1_7=&txtSrcarNo1_8=&txtSrcarNo1_9=&txtSeatNo1_1=&txtSeatNo1_2=&txtSeatNo1_3=&txtSeatNo1_4=&txtSeatNo1_5=&txtSeatNo1_6=&txtSeatNo1_7=&txtSeatNo1_8=&txtSeatNo1_9=&txtDmdSeatAtt1=&txtDmdSeatAtt2=&txtDmdSeatAtt3=&txtDmdSeatAtt4=&txtDmdSeatAtt5=&txtDmdSeatAtt6=&txtDmdSeatAtt7=&txtDmdSeatAtt8=&txtDmdSeatAtt9=&txtDmdSeatAtt1_1=&txtDmdSeatAtt1_2=&txtDmdSeatAtt1_3=&txtDmdSeatAtt1_4=&txtDmdSeatAtt1_5=&txtDmdSeatAtt1_6=&txtDmdSeatAtt1_7=&txtDmdSeatAtt1_8=&txtDmdSeatAtt1_9=&hidRsvChgNo=&hidRsvTpCd=03&txtPsgTpCd1=1&txtPsgTpCd2=3&txtPsgTpCd3=1&txtPsgTpCd4=&txtPsgTpCd5=1&txtPsgTpCd6=&txtPsgTpCd7=1&txtPsgTpCd8=3&txtPsgTpCd9=&txtDiscKndCd1=000&txtDiscKndCd2=000&txtDiscKndCd3=111&txtDiscKndCd4=&txtDiscKndCd5=131&txtDiscKndCd6=&txtDiscKndCd7=112&txtDiscKndCd8=321&txtDiscKndCd9=&txtCompaCnt1=0&txtCompaCnt2=0&txtCompaCnt3=0&txtCompaCnt4=0&txtCompaCnt5=0&txtCompaCnt6=0&txtCompaCnt7=0&txtCompaCnt8=0&txtCompaCnt9=&txtStndFlg=&txtJobId=&txtJrnyCnt=&txtDptStnConsOrdr1=&txtArvStnConsOrdr1=&txtDptStnRunOrdr1=&txtArvStnRunOrdr1=&txtDptStnConsOrdr2=&txtArvStnConsOrdr2=&txtDptStnRunOrdr2=&txtArvStnRunOrdr2=&txtPsrmClCd1=&txtJrnySqno1=&txtJrnyTpCd1=&txtDptDt1=&txtDptRsStnCd1=&txtDptRsStnCdNm1=&txtDptTm1=&txtArvRsStnCd1=&txtArvRsStnCdNm1=&txtArvTm1=&txtTrnNo1=&txtRunDt1=&txtTrnClsfCd1=&txtTrnGpCd1=&txtChgFlg1=&txtDoTrnFlg1=&txtPsrmClCd2=&txtJrnySqno2=&txtJrnyTpCd2=&txtDptDt2=&txtDptRsStnCd2=&txtDptRsStnCdNm2=&txtDptTm2=&txtArvRsStnCd2=&txtArvRsStnCdNm2=&txtArvTm2=&txtTrnNo2=&txtRunDt2=&txtTrnClsfCd2=&txtTrnGpCd2=&txtChgFlg2=&txtDoTrnFlg2=&selGoStartDay=&strHmac=&PageInx=&hidEasyTalk=&hidCapFlag=\n"

const val MAX_COUNT = 3600

enum class KTXTicket(
    val targetName: String,
    val startTime: Int,
    val endTime: Int,
    val url: String,
    val isOnlyKtxOrSRT: Boolean,
) {
    SEOUL_TO_ANDONG_TIKET("서울에서 안동", 900, 1000, SEOUL_TO_ANDONG, true),
//    SUSEO_TO_BUSAN_TIKET("수서에서 부산", 1400, 1700, SUSEO_TO_BUSAN, true),
//    BUSAN_TO_SUSEO_TIKET("부산에서 수서", 1700, 2100, BUSAN_TO_SUSEO, true),
//    SOEUL_TO_JUNJU_TIKET("서울역에서 전주", 1600, 2100, SEOUL_TO_JUNJU, true),
//    YUNGSAN_TO_JUNJU_TIKET("용산역에서 전주", 1400, 1900, YOUNGSAN_TO_JUNJU, true),
}

val telegramBot = TelegramBot(TELEGRAM_BOT_TOKEN)
fun main() {

    val ktxAlarm = KTXAlarm()
    val ktxHttpRequest = OldHttpRequest()
    val startRequest = SendMessage(ADMIN_CHAT_ID, "서버 시작 v10.34")

    telegramBot.execute(startRequest)
    var count = 0
    while (true) {

        val threadList = KTXTicket.entries.map {
            Thread.startVirtualThread { ktxAlarm.sendKtxAlarm(it, ktxHttpRequest) }
        }
        threadList.forEach { it.join() }

        count++
        if (count > MAX_COUNT) {
            val serverHealthRequest = SendMessage(ADMIN_CHAT_ID, "서버 정상")
            telegramBot.execute(serverHealthRequest)
            count = 0
        }
    }
}

